org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official

GROUP=com.timkrest
VERSION_NAME=0.3.0

POM_URL=https://github.com/timkrest/Underlay
POM_SCM_URL=https://github.com/timkrest/Underlay
POM_SCM_CONNECTION=scm:git:git://github.com/timkrest/Underlay.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/timkrest/Underlay.git

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_DEVELOPER_ID=timkrest
POM_DEVELOPER_NAME=Timofey Krestyanov
POM_DEVELOPER_URL=https://github.com/timkrest
